  server:
    port: 5001

  spring:
    jpa:
      # postgreSQL settings
#      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#      show-sql: true
#      hibernate:
#        ddl-auto: update
      #MySQL jpa settings
#      database-platform: org.hibernate.dialect.mysql8dialect
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      # postgreSQL datasource
#      url: jdbc:postgresql://localhost:5432/bankAccount
#      username: postgres
#      password: techbankRootPsw
      # MySQL datasource
      url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
      username: root
      password: 1234
    kafka:
      listener:
        ack-mode: MANUAL_IMMEDIATE
      consumer:
        bootstrap-servers: localhost:9092
        group-id: bankaccConsumer
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: '*'
